### ISSUE TITLE
reloading problem

### ISSUE THREAD

**Issue by horizons2** [AngularYii2/angularyii2.github.io#3]
it would be helpful for newcomers (like me) to angularjs that to fix the 404 reloading problem you have to create a .htaccess file to redirect all requests e.g. /post/2 back to the index.html so that the browser reloading works.

**Comment by githubjeka** [comment]
Thanks. I know it. https://github.com/AngularYii2/angularyii2.github.io/commit/7d9fb35c35c3490f9bf21b374fc69aa7ba8229ff#diff-8052c42ab3b8aa06a3f5f788a4ddccc2L212
But this repository on github.io without apache.

Need to find another solution.

**Comment by horizons2** [comment]
You are right,
I mean a little remark here in the readme would be helpful as you have used the same source also in the yii2 repository. 
https://github.com/githubjeka/angular-yii2

**Comment by githubjeka** [comment]
I added a wiki solution https://github.com/AngularYii2/angularyii2.github.io/wiki/Getting-404-error-on-reloaded-page.

**Comment by arsitek** [comment]
With option 2nd where to replace content in index.html to 404.html, url in menu still refer to "http://localhost/post/published" when it should be "http://localhost/angular-yii2/post/published", and when I put URL manually to it, I got 404 error from apache.

There is something to do in 'app.js' to fix this?

Thank you

**Comment by githubjeka** [comment]
if your code located in subfolder then you should set [`<base>` tag](http://www.w3schools.com/tags/tag_base.asp)

`<base href="http://localhost/angular-yii2/" />` or configurate your virtual server
